plugins {
    id "java"
}

repositories {
    mavenCentral()
    maven { url "https://repo.gradle.org/gradle/libs-releases" } // for gradle-tooling-api
    flatDir { dirs mcreator_path + '/lib' }
    maven {
        url "https://jitpack.io"
    }
    mavenLocal()
}

group = 'org.cdc.pluginmaker'
version = "1.7.10.4"

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

configurations {
    implementation.extendsFrom jarInJar
}

dependencies {
    implementation "org.jboss.forge.roaster:roaster-api:2.31.1.Final"
    implementation "org.jboss.forge.roaster:roaster-jdt:2.31.1.Final"
    implementation "org.snakeyaml:snakeyaml-engine:3.0.1"
    implementation "com.fifesoft:rsyntaxtextarea:3.6.3"
    implementation "com.fifesoft:autocomplete:3.3.3"
    implementation "commons-io:commons-io:2.22.0"
    implementation "org.apache.commons:commons-lang3:3.20.0"
    implementation "org.apache.commons:commons-text:1.15.0"
    implementation "com.formdev:flatlaf:3.7.1:no-natives"
    implementation "org.apache.logging.log4j:log4j-core:2.26.1"
    implementation "org.freemarker:freemarker:2.3.34"
    implementation 'net.mcreator:MCreator:2026.2'
    implementation("com.google.code.gson:gson:2.14.0") {
        dep -> dep.exclude group: 'com.google.errorprone', module: 'error_prone_annotations'
    }

    compileOnly 'org.jetbrains:annotations:26.1.0'
//    jarInJar('com.github.javaparser:javaparser-symbol-solver-core:3.28.1'){
//        exclude group:'org.javassist'
//        exclude group:'com.google.guava'
//    }
}

configurations.jarInJar {
    canBeConsumed = true
    canBeResolved = true
}

processResources {
    filesMatching('plugin.json') {
        expand('version': version)
    }

}

tasks.jar {
    archiveFileName.set('plugin-generator-' + version + '.zip')

    from(project.configurations.jarInJar) {
        into 'META-INF/jarinjar'
    }
}